@appUrl = http://localhost:3000/api
@ordersUserId = 4jc8fzoZbHHnQOI2WMIqiCf4fpChD0lH

### General Health Check no protected
GET {{appUrl}}/health

### openapi 
GET {{appUrl}}/openapi


### 4. Cerrar Sesión (Sign Out)
POST {{appUrl}}/auth/sign-out
Content-Type: application/json
Origin: http://localhost:3000
Referer: http://localhost:3000/

{}

### v1 analytics orders endpoint protected no login
GET {{appUrl}}/v1/analytics/orders?userId={{ordersUserId}}



### 2. Probar Login
POST {{appUrl}}/auth/sign-in/email
Content-Type: application/json
Origin: http://localhost:3000
Referer: http://localhost:3000/

{
    "email": "test@example.com",
    "password": "password123"
}

### 3. Verificar Sesión Actual
GET {{appUrl}}/auth/get-session


### v1 analytics orders endpoint protected 200 ok 
GET {{appUrl}}/v1/analytics/orders?userId={{ordersUserId}}


### v1 analytics orders endpoint protected parameter wrong value 401 unautorized
GET {{appUrl}}/v1/analytics/orders?userId=2

### v1 analytics orders endpoint protected parameter 400 bad request (variable erronea)
GET {{appUrl}}/v1/analytics/orders?userIdd={{ordersUserId}}

### v1 analytics orders endpoint protected parameter mising user 400 bad request
GET {{appUrl}}/v1/analytics/orders

### v1 analytics orders endpoint forced 500 (dev/test only)
GET {{appUrl}}/v1/analytics/orders?forceError=500&userId={{ordersUserId}}

### test swager 
http://localhost:3000/swagger-ui 
